# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FeatureGeometry(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, type: str=None, coordinates: List[List[float]]=None):  # noqa: E501
        """FeatureGeometry - a model defined in Swagger

        :param type: The type of this FeatureGeometry.  # noqa: E501
        :type type: str
        :param coordinates: The coordinates of this FeatureGeometry.  # noqa: E501
        :type coordinates: List[List[float]]
        """
        self.swagger_types = {
            'type': str,
            'coordinates': List[List[float]]
        }

        self.attribute_map = {
            'type': 'type',
            'coordinates': 'coordinates'
        }

        self._type = type
        self._coordinates = coordinates

    @classmethod
    def from_dict(cls, dikt) -> 'FeatureGeometry':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Feature_geometry of this FeatureGeometry.  # noqa: E501
        :rtype: FeatureGeometry
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this FeatureGeometry.


        :return: The type of this FeatureGeometry.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this FeatureGeometry.


        :param type: The type of this FeatureGeometry.
        :type type: str
        """

        self._type = type

    @property
    def coordinates(self) -> List[List[float]]:
        """Gets the coordinates of this FeatureGeometry.


        :return: The coordinates of this FeatureGeometry.
        :rtype: List[List[float]]
        """
        return self._coordinates

    @coordinates.setter
    def coordinates(self, coordinates: List[List[float]]):
        """Sets the coordinates of this FeatureGeometry.


        :param coordinates: The coordinates of this FeatureGeometry.
        :type coordinates: List[List[float]]
        """

        self._coordinates = coordinates
